---
- name: INstall Apache condition
  hosts: localhost

  tasks:
    - name: Install Apache on Ubuntu Server
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
  
    - name: Install Apache on CentOS
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat" 
